### ISSUE TITLE
Misaligned collapsed workspace button

### ISSUE THREAD

**Issue by nanocryk** [Uiniel/zen-mods#4]
When collapsed the workspace button is not aligned with the tab icons.

![image](https://github.com/user-attachments/assets/d79e5f18-8658-477e-ad43-c88c01a3367e)

Adding the following code to my userChrome.css fixes the alignement, however on hover the button snap back to the left before expanding:

```css
@-moz-document url-prefix("chrome:") {
  @media (-moz-bool-pref: "theme.sidebar_expand_on_hover.collapse_buttons") {
    #TabsToolbar:not(#TabsToolbar:hover) {
      #zen-workspaces-button {
        padding-left: 8px !important;
      }
    }
  }
}
```

Result:
![image](https://github.com/user-attachments/assets/6bcb5b1b-9bb2-4277-a0ce-d3f81538c72d)

Otherwise great mod, it looks even better than the original collapse feature :tada:

**Comment by Uiniel** [comment]
The additional spacing is weird I just checked this and for me only the non-workspace buttons add additional spacing leading to a misalignment, but the workspace buttons themself work fine

**Comment by Uiniel** [comment]
@nanocryk How many other buttons are there next to the workspace switcher? I fixed the issue for me, but not sure if it's from the same cause as your issue. For me the issue was fixed by adding this code:
```css
@media (-moz-bool-pref: "theme.sidebar_expand_on_hover.collapse_buttons") {
    #TabsToolbar:not(#TabsToolbar:hover) {
        #zen-sidebar-icons-wrapper {
            justify-content: center !important;
        }
    }
}
```
