### ISSUE TITLE
Option to return the old tab close button

### ISSUE THREAD

**Issue by c0lbarator** [Uiniel/zen-mods#66]
Hi! Is it possible to add an option to return close tab button as in single toolbar layout?

![Image](https://github.com/user-attachments/assets/587150d1-8b9f-45a6-9b9d-e05d76a53599)

After Zen update it is like in collapsed toolbar layout

![Image](https://github.com/user-attachments/assets/4cac4d40-66e9-4705-a18d-5caf63adec8e)

**Comment by antonkarliner** [comment]
Second this. I like your mod very much, but these default close buttons are disgusting...

**Comment by V0LDY** [comment]
They look ugly but having the close button on the right side is terrible if you're using a mod that expands when overing on the left side (or vice versa if you use tabs on the right side).

**Comment by siren15** [comment]
I was looking at the main zen browser issues, and people wanted to remove it completely and modifying this was suggested, add this to the end of your zen-themes.css

```css
.tabbrowser-tab .tab-close-button {
    position: absolute !important;
    top: 10px !important;
    left: 150px !important;
    border-radius: 5px !important;
    min-width: 20px !important;
    min-height: 20px !important;
  } 
```
it's moving the new button to the end of the tab and changes it's design to look closer to the original button, I'm not good with css so you can do your own modifications as you see fit
