### ISSUE TITLE
Turn off sidebar transparency

### ISSUE THREAD

**Issue by antonkarliner** [Uiniel/zen-mods#68]
I don't know if it's something with my browser or is this a built-in mod's feature, but with the latest update the tabs have transparent background on hover, which I personally find a bit distracting... is it possible to switch the transparency off?

<img width="304" alt="Image" src="https://github.com/user-attachments/assets/f45960e5-23b7-45f3-8670-4f303a4be09c" />

**Comment by Uiniel** [comment]
What operating system are you using and what are your theme settings (did you set theme colors)?
(And yeah I have been struggling with the background for a while now, so I'm not really surprised there is another bug I haven't noticed :c )

**Comment by antonkarliner** [comment]
Sorry for not providing details in the initial message. MacOS, I didn't set something specifically, except for the initial setup (screenshot attached).

Btw, thanks for working on this mod, one of my favorites! 

<img width="517" alt="Image" src="https://github.com/user-attachments/assets/51e9c98c-9d73-414b-8d1b-3c136e498525" />

**Comment by Uiniel** [comment]
Thanks! I guess one or more of the css variables I used to get a more (it's still not perfect) seamless looking background isn't set on macos. I don't own a mac so I can't test it myself, but I think adding this to your userChrome.css should fix the issue for now:
```css
#navigator-toolbox::before {
  --zen-main-browser-background: #202020 !important;
  --lwt-accent-color: #202020 !important;
}
```
Not sure which one of these variables is missing, so you probably can remove on of them.
(Also I just color picked the browser background from your screenshot, if someone else needs this workaround you might want to change the color)

**Comment by antonkarliner** [comment]
This worked, thanks!

**Comment by ghost** [comment]
Hi,
I stumbled on the same problem. It only appears on my system (Fedora Workstation with Gnome DE) if I enable the System Theme - auto, so that the browser follows the System Theme (I have that so switch my whole system to light/ dark depending on the time of day)

![Image](https://github.com/user-attachments/assets/115845cd-7952-40d2-a5bf-33d4a0ba84a7)

The solution above doesn't work for light mode because it "hard codes" the bg color to dark, leading to dark text on dark when in light mode. I found a solution to this :

```css
@media (prefers-color-scheme: dark) {
  #navigator-toolbox::before {
    --lwt-accent-color: #202020 !important;
  }
}

@media (prefers-color-scheme: light) {
  #navigator-toolbox::before {
    --lwt-accent-color: #ebebeb !important;
  }
}
```

**Comment by leic4u** [comment]
> Thanks! I guess one or more of the css variables I used to get a more (it's still not perfect) seamless looking background isn't set on macos. I don't own a mac so I can't test it myself, but I think adding this to your userChrome.css should fix the issue for now:
> 
> #navigator-toolbox::before {
>   --zen-main-browser-background: #202020 !important;
>   --lwt-accent-color: #202020 !important;
> }
> 
> Not sure which one of these variables is missing, so you probably can remove on of them. (Also I just color picked the browser background from your screenshot, if someone else needs this workaround you might want to change the color)

Thanks, it works!

**Comment by ghost** [comment]
Upon further testing, it also happens on my windows system, so this problem seem to exist on every desktop OS. 

At least on Windows and Linux where I tested it, it only happens when Zen is set to follow the system theme, so this is probably where the problem originates.

**Comment by zoriya** [comment]
If you use a colored sidebar, adding

```css
html {
	--lwt-accent-color: var(--zen-main-browser-background-toolbar)
}
```

fixes the issue (in both light & dark mode)

**Comment by leic4u** [comment]
> html {
> 	--lwt-accent-color: var(--zen-main-browser-background-toolbar)
> }

Thank you! I tried it and it works!
```css
      #navigator-toolbox::before {
          --zen-main-browser-background: #202020 !important;
          --lwt-accent-color: var(--zen-main-browser-background-toolbar);
      }
```
